version: 2.0
jobs:
 build:
   docker:
     - image: ubuntu:latest
   steps:
     - run:
         name: Setup
         command: |
           add-apt-repository \
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) \
             stable"
           apt-get update && apt-get install -y make docker-ce
